from __future__ import annotations

import html
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

from hsd_run_io import input_path, run_output_dir, write_json, write_text


VERSION = "hsd-legacy-dashboard-compat-v1"
LEGACY_DASHBOARD_STATUS = "replaced_by_operator_command_center"
OUT_DASHBOARD = "dashboard/index.html"
OUT_NOTICE = "legacy_dashboard_replacement.md"
OUT_MANIFEST = "legacy_dashboard_replacement.json"
COMMAND_CENTER_HTML = "operator_command_center.html"
COMMAND_CENTER_MD = "operator_command_center.md"


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def exists(path: str) -> bool:
    return input_path(path).exists()


def command_center_link() -> str:
    if exists(COMMAND_CENTER_HTML):
        return "../operator_command_center.html"
    if exists(COMMAND_CENTER_MD):
        return "../operator_command_center.md"
    return "../operator_command_center.html"


def output_scope() -> str:
    return "run_scoped" if run_output_dir() else "legacy_root"


def manifest() -> Dict[str, Any]:
    run_dir = run_output_dir()
    return {
        "version": VERSION,
        "generated_at_utc": utc_now(),
        "status": LEGACY_DASHBOARD_STATUS,
        "output_scope": output_scope(),
        "output_dir": run_dir.as_posix() if run_dir else ".",
        "replacement": COMMAND_CENTER_HTML,
        "replacement_exists": exists(COMMAND_CENTER_HTML),
        "legacy_dashboard": OUT_DASHBOARD,
        "manual_only": True,
        "auto_publish": False,
    }


def render_html(payload: Dict[str, Any]) -> str:
    link = command_center_link()
    generated = html.escape(payload["generated_at_utc"])
    status = html.escape(payload["status"])
    replacement_exists = "available" if payload["replacement_exists"] else "not created yet"
    replacement_exists = html.escape(replacement_exists)
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="refresh" content="8; url={html.escape(link)}">
<title>Her Sports Daily Legacy Dashboard</title>
<style>
:root {{
  --bg:#10131c; --panel:#f7f7f4; --ink:#17202a; --muted:#5f6975;
  --line:#d9ded9; --accent:#0f766e; --warn:#9a3412;
}}
* {{ box-sizing:border-box; }}
body {{
  margin:0; min-height:100vh; display:grid; place-items:center; padding:24px;
  font-family:Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  color:var(--ink); background:var(--bg);
}}
main {{
  width:min(760px, 100%); background:var(--panel); border:1px solid var(--line);
  border-radius:8px; padding:28px; box-shadow:0 18px 48px rgba(0,0,0,.24);
}}
.kicker {{ color:var(--warn); font-size:12px; font-weight:800; letter-spacing:.08em; text-transform:uppercase; }}
h1 {{ margin:8px 0 12px; font-size:clamp(28px, 5vw, 44px); line-height:1; letter-spacing:0; }}
p {{ color:var(--muted); line-height:1.55; font-size:15px; }}
a {{
  display:inline-flex; align-items:center; justify-content:center; min-height:42px;
  padding:0 14px; border-radius:6px; color:white; background:var(--accent);
  text-decoration:none; font-weight:800;
}}
dl {{ display:grid; grid-template-columns:150px 1fr; gap:8px 14px; margin:20px 0; }}
dt {{ color:var(--muted); font-weight:700; }}
dd {{ margin:0; font-weight:700; }}
@media(max-width:620px) {{ dl {{ grid-template-columns:1fr; }} }}
</style>
</head>
<body>
<main>
  <div class="kicker">Legacy dashboard replaced</div>
  <h1>Use the Daily Operator Command Center</h1>
  <p>The old generic dashboard was built around pre-command-center graphics files. The active local workflow now uses the daily command center as the operator home base.</p>
  <p>This compatibility page is manual-only and does not publish, fetch paid sources, or trigger automation. It redirects after a short pause when the command center exists.</p>
  <dl>
    <dt>Status</dt><dd>{status}</dd>
    <dt>Generated</dt><dd>{generated}</dd>
    <dt>Command center</dt><dd>{replacement_exists}</dd>
  </dl>
  <a href="{html.escape(link)}">Open Command Center</a>
</main>
</body>
</html>"""


def render_notice(payload: Dict[str, Any]) -> str:
    return "\n".join(
        [
            "# HSD Legacy Dashboard Replacement",
            "",
            f"Generated: `{payload['generated_at_utc']}`",
            f"Status: `{payload['status']}`",
            f"Output scope: `{payload['output_scope']}`",
            "",
            "`generate_hsd_dashboard.py` is retained only as a compatibility entrypoint.",
            "The active operator dashboard is `operator_command_center.html`, generated by the manual review stage.",
            "",
            "Guardrails:",
            "",
            "- Manual/local operation remains the default.",
            "- No paid APIs are used.",
            "- No workflow trigger or auto-publishing path is added.",
            "",
        ]
    )


def main() -> None:
    payload = manifest()
    write_text(OUT_DASHBOARD, render_html(payload))
    write_text(OUT_NOTICE, render_notice(payload))
    write_json(OUT_MANIFEST, payload, indent=2)
    print(json.dumps(payload, indent=2))


if __name__ == "__main__":
    main()
